server:
  port: 9001

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://127:0:0:1:3306/account?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver





