spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wage.springcloud.entities
