spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://127:0:0:1:3306/account?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource